.start 0
# Set rF to maxint18
LUI rF, 193709880
ADDI rF, rF, 364
#ADDI rF, r0, 364
:loop
# Decrement counter
ADDI rF, rF, -1
# If result of last operation was positive, jump back to loop
BR.P -1
# OUTPUT
SYSCALLI 'H, OUTPUT
SYSCALLI 'e, OUTPUT
SYSCALLI 'l, OUTPUT
SYSCALLI 'l, OUTPUT
SYSCALLI 'o, OUTPUT
SYSCALLI ', OUTPUT
SYSCALLI 'W, OUTPUT
SYSCALLI 'o, OUTPUT
SYSCALLI 'r, OUTPUT
SYSCALLI 'l, OUTPUT
SYSCALLI 'd, OUTPUT
SYSCALLI '!, OUTPUT
# DUMP
# SYSCALLR rF, DUMP
# HALT
SYSCALLR rF, HALT
